version: "1"

services:
  db:
    container_name: pg_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  todo-backend:
    container_name: backend
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    working_dir: /usr/src/app
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    environment:
      DATABASE_URL: postgres://postgres:mysecretpassword@db:5432/mydb

volumes:
  postgres-data:
